# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 05:55
from __future__ import unicode_literals

# import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buggy', '0005_add_bug_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
